- hosts: localhost
  tasks:
  - name: Create Jenkins Deployment
    community.kubernetes.k8s:
      api_version: apps/v1 
      namespace: default
      definition:
        kind: Deployment 
        metadata:
          name: jenkins-deploy
        spec:
          replicas: 1
          selector:
            matchLabels:
              app: jenkins
          template:
            metadata:
              labels:
                app: jenkins
            spec:
              containers:
              - name: jenkins 
                image: jenkins/jenkins 
                ports:
                - containerPort: 8080
    environment:
        KUBECONFIG: /home/vagrant/.kube/config