- hosts: localhost
  tasks:
  - name: Create Jenkins Deployment
    community.kubernetes.k8s:
      api_version: apps/v1 
      namespace: default
      definition:
        kind: Deployment 
        metadata:
          name: jenkins
        spec:
          replicas: 1
          selector:
            matchLabels:
              app: jenkins
          template:
            metadata:
              labels:
                app: jenkins
            spec:
              nodeName: worker-1
              volumes:
              - name: plugins-v 
                hostPath:
                  path: /jenkins/plugins.txt
              containers:
              - name: jenkins 
                image: jenkins/jenkins
                ports:
                - containerPort: 8080
                # Setup Username and Password ans skip initial setup screen
                env:
                - name: JENKINS_OPTS
                  value: --argumentsRealm.roles.user=admin --argumentsRealm.passwd.admin=admin --argumentsRealm.roles.admin=admin
                - name: JAVA_OPTS 
                  value: -Djenkins.install.runSetupWizard=false
                volumeMounts:
                - name: plugins-v 
                  mountPath: /usr/share/jenkins/plugins.txt
                # Remains 1 step that i couldn't automate correctly which is running /usr/local/bin/install-plugins.sh < /usr/share/jenkins/plugins.txt
                # For now k exec -it jenkins-  -- bash
                # /usr/local/bin/install-plugins.sh < /usr/share/jenkins/plugins.txt
    environment:
        KUBECONFIG: /home/vagrant/.kube/config