---
# vars file for infra
region: us-east-1 
controller_ports:
- description: "SSH"
  port: 22 
- description: "Kubelet API"
  port: 10250
- description: "Kube-scheduler"
  port: 10251
- description: "Kube-controller-manager"
  port: 10252
- description: "etcd server client API"
  port: 2379
- description: "etcd server client API"
  port: 2380
- description: "Kubernetes API server"
  port: 6443
# - 22     # SSH 
# - 10250  # Kubelet API
# - 10251  # Kube-scheduler  
# - 10252  # Kube-controller-manager 
# - 2379   # etcd server client API
# - 2380   # etcd server client API
# - 6443   # Kubernetes API server

nat_instance_id: ami-00a9d4a05375b2763
redhat_instance_id: ami-098f16afa9edf40be

private_subnet_ec2_instances:
- name: kubernetes_controller_instance
  sg: kubernetes_controller_SG
- name: kubernetes_worker_instance
  sg: kubernetes_worker_SG 